import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Aside } from "@/components/aside";
import { ClassProvider } from "@/context/ClassContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard | Pulse Mais",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {  
  
  return (
    <html lang="pt-br">
      <body className={inter.className + " bg-gray-100 h-screen"}>
        <main className="flex flex-row h-full overflow-hidden">
          <Aside />
          <div className="flex-1 overflow-auto p-4">
            <ClassProvider>
              {children}
            </ClassProvider>
          </div>
        </main>
      </body>
    </html>
  );
}
